[bridge]
controller_transport = "websocket"
serial_port = ""
controller_udp_port = 9001
controller_websocket_port = 8001
host_transport = "udp"
host_udp_port = 9000
host_websocket_port = 8000
log_broadcast_port = 9999

[logs]
max_entries = 200
export_max = 2000

[ui]
default_filter = "All"
