# Teensy USB Development Board
# https://www.pjrc.com/teensy/
#
# Supported boards:
# - Teensy 4.0, 4.1 (PID 0x0483)
# - Teensy 3.x (PID 0x0483)
# - Teensy LC (PID 0x0486)
# - Teensy MicroMod (PID 0x0489)

[device]
name = "Teensy"
vid = 0x16C0
pid_list = [0x0483, 0x0486, 0x0487, 0x0489]

# Official PJRC udev rules from https://www.pjrc.com/teensy/00-teensy.rules
udev_rules = """
# UDEV Rules for Teensy boards, http://www.pjrc.com/teensy/
# The latest version of this file may be found at: https://www.pjrc.com/teensy/00-teensy.rules

ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04*", ENV{ID_MM_DEVICE_IGNORE}="1", ENV{ID_MM_PORT_IGNORE}="1"
ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04[789a]*", ENV{MTP_NO_PROBE}="1"
KERNEL=="ttyACM*", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04*", MODE:="0666", RUN:="/bin/stty -F /dev/%k raw -echo"
KERNEL=="hidraw*", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04*", MODE:="0666"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="04*", MODE:="0666"
KERNEL=="hidraw*", ATTRS{idVendor}=="1fc9", ATTRS{idProduct}=="013*", MODE:="0666"
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1fc9", ATTRS{idProduct}=="013*", MODE:="0666"
"""

[device.name_hint]
macos = "usbmodem"
linux = "ttyACM"
